version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/MeanStackCICD
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 900
      runas: ec2-user
