version: "3.8"
services:
  meancicd_app:
    container_name: MeanCICD
    build: .
    restart: always
    ports:
      - 5000:5000
    healthcheck:
      test: "exit 0"
    #environment:
      #MONGO_URI: "${MONGO_URI}"
      #PORT: "${PORT}"
  
